name: cd pipeline

on:
  workflow_run:
    workflows: [ "ci pipeline" ]
    types:
        - completed

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Pull Docker image
      run: sudo docker pull kedar2003/otc-backend:latest
    - name: Delete Old docker
      run: sudo docker rm -f otc-backend-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 8080:8080 --name otc-backend-container kedar2003/otc-backend
      
    